name: Publish Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    container: git.sanjairocky.in/rncp/docker-alpine:main
    runs-on: ubuntu-latest
    env:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      GIT_SSL_NO_VERIFY: true
      registry: registry.sanjairocky.in
      RUNNER_TOOL_CACHE: /toolcache
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
        with: # replace it with your local IP
          config-inline: |
            [registry."${{ env.registry }}"] 
              http = true
              insecure = true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        env:
          # Force this action to use the container trust store
          NODE_OPTIONS: --use-openssl-ca
          DOCKER_CLI_ACI_OFFICIAL: "1"
          DOCKER_BUILDKIT: "1"
          DOCKER_TLS_CERTDIR: ""
          DOCKER_TLS_VERIFY: 0
        with:
          images: ${{ env.registry }}/${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
